

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PeepsOne from '../public/images/Peeps_One.png'
import PeepsTwo from '../public/images/Peeps_Two.png'
import PeepsLogo from '../public/images/Peeps_Logo.png'
import Discord from '../public/images/Discord.png'
import Twitter from '../public/images/Twitter.png';
import Opensea from '../public/images/Opensea.png'
import Instagram from '../public/images/Instagram.png'

import Swiper from 'swiper';
import 'swiper/css'; 

import { ADDRESS,ABI } from '../constants'
import React, {useState, useEffect, useRef} from 'react'; 
import {ethers, providers, Contract, utils, BigNumber} from 'ethers'; 
import Web3modal from 'web3modal';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  

  const [isConnected, setIsConnected] = useState(false); 
  let [accountAddress, setAccountAddress] = useState("");
  const [setLoading, isLoading] = useState(false); 
  const [tokenCost, setTokenCost] = useState("")
  const [tokenAmount, setTokenAmount] = useState(0)

  const web3modal = useRef(); 


  useEffect(() => {
    web3modal.current = new Web3modal(
      {
        network: "mumbai", 
        providerOptions: {},
        disableInjectedProvider: false
      }
    )
  })


//This functino splits the string 
const splitString = string => { 
  let result1 = string.substring(0,5) //gets the first 5 charactesr of string 
  let result2 = string.substring(38, string.lenght) // lets the last 5? dendingon the length of array 
  let finalResult = result1 + "..." + result2 //concact them together 
  return finalResult;

}
let address_account 
  //get provider or Signer 
  const getProviderOrSigner = async(needSigner = false) => { 
    const provider = await web3modal.current.connect()
    const web3provider = new providers.Web3Provider(provider)

    const signer =  web3provider.getSigner();
    const address = await  signer.getAddress();
    const substringAddress = splitString(address);
    address_account = substringAddress
    console.log(substringAddress)
    setAccountAddress(substringAddress);
    //check if connected currenlty to the right chainID
    //set it in brackets because chainID is an object 
    const {chainId} = await web3provider.getNetwork();
    if(chainId !== 137) { 
      // window.alert("You are on the wrong network, switch to rinkeby")
    }

    if(needSigner) { 
      const signer = web3provider.getSigner(); 
      return signer;
    }

    return address_account;
    return web3provider;
  }

  const connect = async() => 
  { 
    try {
      await getProviderOrSigner();
      setIsConnected(true); 
    }catch(e)
     { 
      console.error(e)
     }
  }


  

  //Read balance contract:
  const read_balance = async() => 
  { 
    try{ 
        const provider = await getProviderOrSigner(true); 
        const contract = new Contract(
          ADDRESS,
          ABI,
          provider
        )
          const balance = parseInt((await contract.cost()).toString())
          console.log(balance)
        


    }catch(e)
    { 
      console.error(e)
    }
  } 
  const mint = async() => 
  { 
    try{ 
        const provider = await getProviderOrSigner(true); 
        const contract = new Contract(
          ADDRESS,
          ABI,
          provider
        )
        
          const balance = await contract.mint(1,{value: utils.parseUnits("50")},)
          setLoading(true); 
          console.log(balance)
    }catch(e)
    { 
      console.error(e)
    }
  } 






const returnAdress = () => 
{ 
  if(isConnected === true)
  {
    return(
      
      <div onClick={connect} className = {styles.linkContainer}>
      <a className = {styles.header_links}>{accountAddress}</a>
    </div>
    )
  }else 
  { 
    return(
      <div onClick={connect} className = {styles.linkContainer}>
      <a className = {styles.header_links}>CONNECT WALLET</a>
    </div>
    )
  }
}




//Swiper Code 

const swiper = new Swiper('.swiper', {
  // Optional parameters
  direction: 'horizontal',
  // loop: true,

  // If we need pagination
  pagination: {
    el: '.swiper-pagination',
  },

  // Navigation arrows
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },

  // And if we need scrollbar
  scrollbar: {
    el: '.swiper-scrollbar',
    draggable: true
  },
});

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Pushin Peeps</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/Peeps_Logo.png" />
      </Head>

      <nav className = {styles.nav}>
      <div className = {styles.slider_wrapper}>
        <div className={styles.item_holder}>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>

            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image  className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image   className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image   className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
                

                </div>
    
        <div className={styles.item_holder}>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image   className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>

            
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image  className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
    
                

                </div>
    
                
              
          </div>

      </nav>


      <header className={styles.main}>

          <div className = {styles.heroContainer}>
          <div className = {styles.linkContainer}>

                    <a className = {styles.header_links} href = "#">
                      <Image src = {Discord} alt = "Discord" />
                        <span>JOIN US</span>
                      
                      </a>
                  </div>

              <div className = {styles.container}> 

               
                    <div className = {styles.header}>
                        <Image src = {PeepsLogo} alt = "peepslogo" />
                    </div>



              </div>

              {returnAdress()}
              {/* <div onClick={connect} className = {styles.linkContainer}>
                    <a className = {styles.header_links}>CONNECT WALLET</a>
                  </div> */}

            </div>   



      </header>


    <div className = {styles.container}>
      <div className = {styles.hero}>
            <h1 className={styles.widthLarge}>Fostering A Web3 Community Of Validation</h1>
            <p className = {styles.sub}>Utilzing growth through decentralized proposals, partnerships and creative utility.</p>
              <label>How many ?</label>

            <div className = {styles.buttonRow}>
              <input className = {styles.input} type = "number" placeholder = "How Many"
              onChange = {(e) => setTokenAmount(e.target.value)}
              />
              <button
                disabled = {!tokenAmount > 0}
              onClick={() => mint(tokenAmount)} className = {styles.mint}>MINT</button>
                <span  className = {styles.center}>10 MATIC</span>

            
            </div>


          </div>

    </div>


    <div className = {`${styles.slider_wrapper} ${styles.margin_top}`}>
        <div className={styles.item_holder}>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>

            
            <div className={styles.items}>
              <Image  className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image   className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image   className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
    
                

                </div>
    
        <div className={styles.item_holder}>
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image   className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>

            
            <div className={styles.items}>
              <Image className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
            <div className={styles.items}>
              <Image  className = {styles.item} alt = "peepsOne" src = {PeepsTwo} />
              <Image  className = {styles.item} alt = "peepsTwo" src = {PeepsOne} />
                      
            </div>
    
                

                </div>
    
                
              
          </div>


          <div className = {styles.container}>
      <div className = {styles.hero}>
            <h1>Pushing Towards Future Of Web3</h1>

            <div >
              <p>PushinPeeps is fostering the growth through decentralized proposals, parthnerships and creative utility by growing their very own community of Web3 Ethusiast.</p>
            </div>
      


          </div>

    </div>


    <div className = {styles.sideBarWrapper}>
        <div className = {styles.grid_column}>
          <div className = {styles.grid_items}>
              <p>How do I obtain Polygon Matic in my cryto wallet?</p>
              <p>There are a multitude of ways to do this. One of the simplest ways we use is by making a Crypto.com account then purchase Polygon Matic on there. Once you get transaction you can send it to your Metamask Polygon Matic wallet. Very simple that route. However nothing in this discord is financial advice. Be careful and pay attention to anything you do regarding crypto currencies and NFTs.</p>

          </div>
   
          <div className = {styles.grid_items}>
              <p>What will the crypto I spend be used in the project?</p>
              <p>15% will go to charity of risk youth living in alternative housing. 30% will be designated to Team Peeps budget 20% will be threshold for project funds. 30% will be used for project legalities. Remaining 5% will be reserved for community raffles of exclusive itmes.</p>

          </div>
   
          <div className = {styles.grid_items}>
              <p>Where can i see PV2 NFTS after I Mint/Purchase them?</p>
              <p>You find find the NFTs in your Opensea wallet once connected</p>
              <button className = {`${styles.mint} ${styles.margin_top}`}>FOLLOW US</button>

          </div>
   
          <div className = {styles.grid_items}>
              <p>What perks/utilities do I gain from owning a PV2 NFT</p>
              <p>Whether you own one or multiple the NFTs/utilities apply the same community will take votes on certain traits, number, or even quantity that will be eligible for giveaways/Raffles. For example one week it can be even or odd number NFTs or Glasses Trait holders that will only be eligible to claim Entry Via Utility Dashboard Tropee.</p>

          </div>

   
        </div>


    </div>

    <div className = {styles.row}>

      <a className = {`${styles.margin_top} ${styles.mint}`}>MINT</a>

    </div>
    {/* MOBILE SWIPER */}

    <div className = {styles.cardContainerMobile}>

        <div class="swiper">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
            <div className = {`${styles.cardOne} ${styles.card}`}>
                </div>
            </div>
            <div class="swiper-slide">
            <div className = {`${styles.cardTwo} ${styles.card}`}>

</div>
            </div>
            <div class="swiper-slide">
    <div className = {`${styles.cardThree} ${styles.card}`}>
              
            </div>
            </div>
            ...
          </div>
          <div class="swiper-pagination"></div>

          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>

          <div class="swiper-scrollbar"></div>
        </div>
              </div>                


    {/* MOBILE SWIPER */}
    <div className = {styles.cardContainer}>

        <div className = {styles.card_flex}>

            <div className = {`${styles.cardOne} ${styles.card}`}>

            </div>
            <div className = {`${styles.cardTwo} ${styles.card}`}>

            </div>
            <div className = {`${styles.cardThree} ${styles.card}`}>
              
            </div>


        </div>




    </div>


    
    <div className = {styles.container}>
      <div className = {`${styles.hero}`} >
            <h1 className={`${styles.widthLarge} ${styles.margin_top}`}>Web3 Community with tools. Utility Dashboard and Ecoysystem. Digital Collectors Have Been Dreaming Of.</h1>
          </div>


  
          <div className = {styles.sideBarWrapper}>
        <div className = {styles.grid_column}>
          <div className = {styles.grid_items}>
              <p>Additonal Perks & Utilites</p>
              <span className = {styles.thin}>More than a strong community we are excited  about the utilities we are offering </span>
             <ul>
              <li><strong>Pick Topics-</strong> Vote on some of the topics we dive into discuss with the community</li>
              <li><strong>Private Events-</strong> Gain access to private critique and Q&A sessions through the year</li>
              <li><strong>Discord Role-</strong> Have the option to sign into discord bot to receive access to exclusive channel and content and conversations</li>
              <li><strong>Metaverse Utilities-</strong> pace Airdrops, and Digital Asset clothing.
</li>
              <li><strong>Secondary Market-</strong> Peeps Welcome reselling on the Opensea secondary market.</li>
             </ul>

          </div>
  
   
          <div className = {styles.grid_items}>
              <p>PV2NFT is Official Member Id Token to the PushinPeeps Community  T</p>
              <li>How long you hold, the quantity, the traits all play a part of your experience within the PushinPeeps community..</li>
              <li>Peeps Utility is Powered by Tropee. This dashboard will run all utility Campaigns. Simply connect your holders wallet and claim.</li>

          </div>

   
        </div>



    </div>


    </div>

    <div className = {styles.row}>

<a href = "https://pushinpv2.tropee.com/" className = {`${styles.margin_top} ${styles.mint}`}>Utilty Dashboard</a>

</div>
    <footer className = {styles.footer}>

      <div className ={styles.footerHeading}>
        <div className = {styles.footerHeadingWrapper}>
          <h2>PUSHIN P</h2>
        </div>
      </div>

      <div className = {styles.flexBox}>
      <span className = {styles.thin}>DOA Labs</span>

        <div className = {styles.footerFlexRow}>
          <Image  className = {styles.footerImages} src = {Twitter} alt = "twitter" />
          <Image   className = {styles.footerImages}  src = {Opensea} alt = "twitter" />
          <Image    className = {styles.footerImages} src = {Instagram} alt = "twitter" />
      
        </div>
      </div>

    </footer>

   

    </div>
  )
}
